### ISSUE TITLE
Raw Counts of integrated scDatasets

### ISSUE THREAD

**Issue by jkbenotmane** [ccruizm/GBmap#1]
Hello, 
Thank you for curating this phenomenal scAtlas of Glioblastoma. 
I wonder if the raw Counts of the unintegrated datasets are still stored somewhere in the GBmap Core atlas ?

**Comment by ccruizm** [comment]
Hello @jkbenotmane ,

Glad to hear you find it useful! The raw counts are stored either in the slot 'counts' of the Seurat object or the 'counts' layer in an AnnData object. You can download either from cellxgene (which contains the full gene set) or from Zenodo (this one contains the 5000 HVG only). To obtain the raw counts you can use `GetAssayData(GBmap, slot = 'counts')` (Seurat) or `GBmap.layers["counts"]` (AnnData).

Let me know please whether you have any additional questions.

**Comment by jkbenotmane** [comment]
Hello @ccruizm,
thank you for responding so quickly!

Though i still have problems... 
I downloaded the cellxgene core & extended gbmap and in neither anndata obj did I find the layer['counts'], Core only has layer 'scaled' and the extended map has no layer.
It is probably my mistake, though I don´t find i myself...

core gbmap:
AnnData object with n_obs × n_vars = 338564 × 28045
    obs: 'author', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'ethnicity_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'sex_ontology_term_id', 'stage', 'location', 'sector', 'sample', 'celltype_original', 'iCNV', 'EGFR', 'MET', 'p53', 'TERT', 'ATRX', 'PTEN', 'MGMT', 'KI_67', 'chr1p19q', 'PDGFR', 'suspension_type', 'donor_id', 'annotation_level_3', 'annotation_level_4', 'annotation_level_2', 'annotation_level_1', 'tissue_ontology_term_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'ethnicity', 'development_stage'
    var: 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'feature_biotype', 'feature_is_filtered', 'feature_name', 'feature_reference'
    uns: 'X_approximate_distribution', 'X_normalization', 'batch_condition', 'default_embedding', 'hvg', 'schema_version', 'title'
    obsm: 'X_umap'
    layers: 'scaled'

extended gbmap
AnnData object with n_obs × n_vars = 1135677 × 26355
    obs: 'author', 'donor_id', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'ethnicity_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'sex_ontology_term_id', 'annotation_level_1', 'annotation_level_2', 'annotation_level_3', 'gbmap', 'method', 'stage', 'location', 'sector', 'celltype_original', 'EGFR', 'MET', 'p53', 'TERT', 'ATRX', 'PTEN', 'MGMT', 'chr1p19q', 'PDGFR', 'suspension_type', 'tissue_ontology_term_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'ethnicity', 'development_stage'
    var: 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'feature_biotype', 'feature_is_filtered', 'feature_name', 'feature_reference'
    uns: 'X_approximate_distribution', 'X_normalization', 'batch_condition', 'cell_type_ontology_term_id_colors', 'default_embedding', 'hvg', 'schema_version', 'title'
    obsm: 'X_umap'

Edit:
The raw counts are indeed present but only in the scarches integrated file holding hvg:

AnnData object with n_obs × n_vars = 338564 × 5000
    obs: 'author', 'patient', 'method', 'CellID', '_scvi_batch', '_scvi_labels', '_scvi_local_l_mean', '_scvi_local_l_var'
    var: 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: '_scvi', 'hvg'
    layers: 'counts'

**Comment by ccruizm** [comment]
Sorry for that. I thought the objects from cellxgene both contained that layer. I have downloaded the files and checked them. The raw counts are stored in `adata.raw.X` and normalized counts in `adata.X`. I hope you do not encounter any more issues.

**Comment by jkbenotmane** [comment]
Thank you that solved it!
